"""Build a solver-labeled position corpus.

Each record: size, moves (game so far), to_move, winner (perfect play),
winning_moves (for to_move), n_stones. Positions generated by random playouts
(uniform legal moves) truncated at random depth — varied, unbiased by any policy.
"""

import argparse
import json
import os
import random
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hexenv.board import Board, EMPTY, BLACK, WHITE
from hexenv.positions import random_position
from hexenv.solver import HexSolver


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, required=True)
    ap.add_argument("--n", type=int, default=200, help="positions per stone-count bucket")
    ap.add_argument("--stones", type=str, default=None,
                    help="comma-separated stone counts; default spread for size")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    if args.stones:
        buckets = [int(s) for s in args.stones.split(",")]
    else:
        top = args.size * args.size
        buckets = sorted({1, 2, 4, 6, 8, min(12, top - 6), min(16, top - 4)})

    rng = random.Random(args.seed)
    solver = HexSolver()
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)

    seen = set()
    t_start = time.time()
    n_written = 0
    with open(args.out, "w") as f:
        for n_stones in buckets:
            for i in range(args.n):
                b = random_position(args.size, n_stones, rng)
                key = tuple(sorted((c, cell) for c, cell in b.moves)) + (b.to_move,)
                if key in seen:
                    continue
                seen.add(key)
                t0 = time.time()
                wins = solver.winning_moves(b)
                dt = time.time() - t0
                winner = b.to_move if wins else (WHITE if b.to_move == BLACK else BLACK)
                f.write(json.dumps({
                    "size": args.size,
                    "n_stones": n_stones,
                    "moves": [["B" if c == BLACK else "W", cell] for c, cell in b.moves],
                    "to_move": "B" if b.to_move == BLACK else "W",
                    "winner": "B" if winner == BLACK else "W",
                    "winning_moves": wins,
                    "n_legal": len(b.legal_moves()),
                    "solver_s": round(dt, 3),
                }) + "\n")
                n_written += 1
            print(f"bucket {n_stones} stones done, {n_written} total, "
                  f"{time.time()-t_start:.0f}s elapsed", flush=True)
    print(f"wrote {n_written} positions to {args.out}")


if __name__ == "__main__":
    main()
